version: '3.9'

services:
  selenium:
    image: selenium/standalone-chrome
    shm_size: 2gb
    # Ports if needed outside of docker stack
    # ports:
    #   - "4444:4444"
    #   - "7900:7900"
  paperboy:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    restart: unless-stopped
    volumes:
      - ./key.json:/key.json
      - ./articles:/app/src/articles
      - ./db.sqlite:/app/src/db.sqlite
    env_file:
      - .env
