version: '3.9'

services:
  selenium:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.selenium
    privileged: true
    shm_size: 2gb
    restart: unless-stopped
    # Ports if needed outside of docker stack
    ports:
      - "7900:7900"
      - "4444:4444"
    profiles:
      - selenium

  paperboy:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    shm_size: 2gb
    restart: unless-stopped
    volumes:
      - ./key.json:/key.json
      - ./articles:/app/src/articles
      - ./db.sqlite:/app/src/db.sqlite
    env_file:
      - .env
    profiles:
      - app
